### ISSUE TITLE
Problem with the login

### ISSUE THREAD

**Issue by NLS24** [selleronom/mittfortum#2]
All right, so first of all this install does not show up in the latest version of HACS, but I managed to install it and get to the login instance. But the first field does not specify what you want me to enter so I'm guessing it would be my email address? The metering point, I am guessing is the Anläggnings ID? And then the last of all your city name, I'm guessing is the post ort? So let's just say that all the following questions are a Yes, I am still not able to login.

**Comment by selleronom** [comment]
@NLS24 The login method used in the plugin is broken at the moment because MittFortum changed the way logins are handled. 

As a temporary fix you can use a refresh_token as your username, check #1 for instructions. Hope to release a version that handles logins directly from Home Assistant in the future :)

**Comment by Jerra94** [comment]
@NLS24 
I have been trying to setup the plugin and the metering point is apparently NOT the anläggningsid. In devtools you will find a similar request to the one that this integration uses. My meteringpoint was only 6 digits and I found it by searching "metering" in the network tab in the browser's dev tools.

**Comment by NLS24** [comment]
So I managed to login according to #1.

I only get two sensors. one is total consumption and the other one is total cost.

But I have no idea how to get values from any of them? I am not getting any historical data?

Any new instructions on set up after the update?

**Comment by selleronom** [comment]
@NLS24 The sensors will try to fetch the total of energy and cost which is for me updated once a day. You can use the sensors for the Energy dashboard. 

The login flow has been updated to use username and password instead of refresh_token, you need to delete the integration and add it again. 

@Jerra94 Will release an update that extracts your metering and customer id automatically...
