### ISSUE TITLE
Unable to use refresh token to get data

### ISSUE THREAD

**Issue by DJKatastrof** [selleronom/mittfortum#3]
Hey

Is this being worked on since their update? 
I am able to get initialize a session with refresh token, but no data is updating.

**Comment by selleronom** [comment]
@DJKatastrof The login flow has been updated so username and password is now used instead of refresh_token. You need to delete the integration and add it again for it to work. 

Will release an update which will let you pick your customer and metering ID but as of now you have to enter the correct values for that yourself, check your browser developer tools to find it. Perhaps any of the IDs is incorrect?

**Comment by DJKatastrof** [comment]
Hey!

I saw that an update was released, thank you! 
Yea, the meter ID was wrong. I was able to receive it from the developer tools by search for "meter" and grab the först short number 👍 

Another question, I can only see total cost and yearly energy consumption. Is there any easy way I can view my daily energy consumption?

**Comment by selleronom** [comment]
Good to hear!

As of now the integration fetches the total yearly consumption but the plan is to add support to fetch the hourly data from the previous day.
